server:
  port: 8090  #用户鉴权登录端口
spring:
  application:
    name: OAuth-SSO
#    boot:
#      admin:
#        url: http://localhost:3306
  datasource:
    #        name: test
    url: jdbc:mysql://127.0.0.1:3306/docker-user?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=round&allowMultiQueries=true
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
    #监控统计用的filter:stat
    #日志用的filter:log4j
    #防御sql注入的filter:wall
    filters: stat,wall
    #最大连接池数量
    maxActive: 100
    #初始连接数
    initialSize: 5
    #获取链接超时时间为1分钟，单位为毫秒。
    maxWait: 60000
    #配置5,当线程池数量不足，自动补充。
    minIdle: 5
    #1.Destroy线程会检测连接的间隔时间
    #2.testWhileIdle的判断依据
    timeBetweenEvictionRunsMillis: 60000
    #一个链接生存的时间（默认的值：25200000，换算后的结果公式是：300000/1000/60 = 5分钟）
    minEvictableIdleTimeMillis: 300000
    #检测数据库链接是否有效，必须配置
    validationQuery: select 'x'
    #此项配置为true即可，不影响性能，并且保证安全性。意义为：申请连接的时候检测，
    #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    testWhileIdle: true
    #获取链接的时候，不校验是否可用，开启会有损性能
    testOnBorrow: false
    #归还链接到连接池的时候校验链接是否可用
    testOnReturn: false
    poolPreparedStatements: true
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    #在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    maxOpenPreparedStatements: 20
    #链接回收的时候控制台打印信息，测试环境可以加上true，线上环境false。会影响性能。
    log-abandoned: true
    maxPoolPreparedStatementPerConnectionSize: 20
    http:
      encoding:
        charset: utf-8
        enabled: true
        force: true